### ISSUE TITLE
Missing Credentials in config

### ISSUE THREAD

**Issue by imZEH** [orangewise/s3-zip#6]
E:\Projects_2016\node_modules\s3-files\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

TimeoutError: Missing credentials in config
    at ClientRequest.<anonymous> (E:\Projects_2016\node_modules\s3-files\node_modules\aws-sdk\lib\http\node.js:56:34)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:614:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:333:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

I paste the sample code on my project similar to this
s3Zip
  .archive({ region: region, bucket: bucket}

I log also region and bucket and got a value .
could you help about the error.
Thank You in advance.

**Comment by orangewise** [comment]
Hi @imZEH, I think you should setup your credentials as mentioned (in the readme :), you can find them here: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/configuring-the-jssdk.html
