### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by rad182** [orangewise/s3-zip#60]
Hi! I'm trying to to zip around 400+ files with average of 28MB each that's probably around 7GB and I'm getting this error.

Currently running these using EC2 m5.large.

Any suggestion or workaround regarding this memory issue? TIA

```
throw err;
^
RangeError: Array buffer allocation failed
at new ArrayBuffer (<anonymous>)
at new Uint8Array (<anonymous>)
at new FastBuffer (internal/buffer.js:941:1)
at createUnsafeBuffer (buffer.js:115:12)
at allocate (buffer.js:308:10)
at Function.allocUnsafe (buffer.js:273:10)
at Function.concat (buffer.js:452:25)
at bufferConcat (/app/node_modules/concat-stream/index.js:117:17)
at ConcatStream.getBody (/app/node_modules/concat-stream/index.js:64:42)
at ConcatStream.<anonymous> (/app/node_modules/concat-stream/index.js:37:51)
at ConcatStream.emit (events.js:205:15)
at ConcatStream.EventEmitter.emit (domain.js:471:20)
at finishMaybe (/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:620:14)
at endWritable (/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:629:3)
at ConcatStream.Writable.end (/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:567:22)
at PassThrough.onend (_stream_readable.js:675:10)
at Object.onceWrapper (events.js:288:20)
at PassThrough.emit (events.js:205:15)
at PassThrough.EventEmitter.emit (domain.js:471:20)
at endReadableNT (_stream_readable.js:1154:12)
at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by orangewise** [comment]
Hi @rad182, I don’t think this error is related to this module...
